export default {
  /** 主体公司 */
  AUTOCOMPLETE_KEY_PRINCIPAL: 'PRINCIPAL',
  /** 主体公司(境外) */
  AUTOCOMPLETE_KEY_PRINCIPAL_EN: 'PRINCIPAL_EN',
  /** 供应商 */
  AUTOCOMPLETE_KEY_SUPPLIER: 'SUPPLIER',
  /** 客户 */
  AUTOCOMPLETE_KEY_CUSTOMER: 'CUSTOMER',
  /** 报关行 */
  AUTOCOMPLETE_KEY_CUSTOMS: 'CUSTOMS',
  /** 承运方 */
  AUTOCOMPLETE_KEY_TRANSPORT: 'TRANSPORT',
  /** 资金方 */
  AUTOCOMPLETE_KEY_FUNDERS: 'FUNDERS',
  /** 客户开票资料 */
  AUTOCOMPLETE_KEY_CUS_MAKE_INVOICE: 'CUS_MAKE_INVOICE',
  /** 企业信息 */
  AUTOCOMPLETE_KEY_COMPANY: 'COMPANY',
  /** 用户管理 */
  AUTOCOMPLETE_KEY_CONSUMER: 'CONSUMER',
  /** 商务信息 */
  AUTOCOMPLETE_KEY_TRADEMAN: 'TRADEMAN',
  /** 业务信息 */
  AUTOCOMPLETE_KEY_SALEMAN: 'SALEMAN',
  /** CIQ代码 */
  AUTOCOMPLETE_KEY_CIQ_CODE: 'CIQ_CODE',
  /** 税收分类 */
  AUTOCOMPLETE_KEY_TAX_CATEGORY: 'TAX_CATEGORY',
  /** 费用类目 */
  AUTOCOMPLETE_KEY_COST_ITEM: 'COST_ITEM',
  /** 销售客户 */
  AUTOCOMPLETE_KEY_CUS_CUSTOMER: 'CUS_CUSTOMER',
  /** 服务协议 */
  AUTOCOMPLETE_KEY_SERVICE_AGREE: 'SERVICE_AGREE',
  /** 服务协议模板 */
  AUTOCOMPLETE_KEY_SERVICE_AGREE_TEMPLATE: 'SERVICE_AGREE_TEMPLATE',
  /** 客户交货信息 */
  AUTOCOMPLETE_KEY_CUS_DELIVERY: 'CUS_DELIVERY',
  /** 商品-型号 */
  AUTOCOMPLETE_KEY_PRODUCT_MODEL: 'PRODUCT_MODEL',
  /** 商品-单位 */
  AUTOCOMPLETE_KEY_PRODUCT_UNIT: 'PRODUCT_UNIT',
  /** 仓库 */
  AUTOCOMPLETE_KEY_WAREHOUSE: 'WAREHOUSE',
  /** 币别 */
  AUTOCOMPLETE_KEY_CURRENCY: 'CURRENCY',
  /** 币制代码 */
  AUTOCOMPLETE_KEY_CCL_CURRENCY: 'CCL_CURRENCY',
  /** 成交方式 */
  AUTOCOMPLETE_KEY_CCL_TRANSACTION_MODE: 'CCL_TRANSACTION_MODE',
  /** 运输方式 */
  AUTOCOMPLETE_KEY_CCL_TRANSPORT: 'CCL_TRANSPORT',
  /** 包装种类 */
  AUTOCOMPLETE_KEY_CCL_WRAP_TYPE: 'CCL_WRAP_TYPE',
  /** 国别(地区)代码 */
  AUTOCOMPLETE_KEY_CCL_COUNTRY: 'CCL_COUNTRY',
  /** 港口代码 */
  AUTOCOMPLETE_KEY_CCL_DISTINATE_PORT: 'CCL_DISTINATE_PORT',
  /** 计量单位代码 */
  AUTOCOMPLETE_KEY_CCL_UNIT: 'CCL_UNIT',
  /** 国内(地区)代码 */
  AUTOCOMPLETE_KEY_CCL_DISTRICT: 'CCL_DISTRICT',
  /** 关区代码 */
  AUTOCOMPLETE_KEY_CCL_CUSTOMS: 'CCL_CUSTOMS',
  /** 出入境口岸代码 */
  AUTOCOMPLETE_KEY_CCL_ENTY_PORT_CODE: 'CCL_ENTY_PORT_CODE',
  /** 集装箱规格 */
  AUTOCOMPLETE_KEY_CCL_CONTAINER_FORMAT: 'CCL_CONTAINER_FORMAT',
  /** 征免性质 */
  AUTOCOMPLETE_KEY_CCL_LEVY_TYPE: 'CCL_LEVY_TYPE',
  /** 监管方式 */
  AUTOCOMPLETE_KEY_CCL_TRADE: 'CCL_TRADE',
  /** 国内行政区划（目的地） */
  AUTOCOMPLETE_KEY_CCL_DEST_CODE: 'CCL_DEST_CODE',
  /** 征减免税 */
  AUTOCOMPLETE_KEY_CCL_LEVYMODE: 'CCL_LEVYMODE',
  /** 检验检疫机关 */
  AUTOCOMPLETE_KEY_CCL_ORG_CODE: 'CCL_ORG_CODE',
  /** 原产地区 */
  AUTOCOMPLETE_KEY_CCL_ORIG_PLACE_CODE: 'CCL_ORIG_PLACE_CODE',
  /** 用途 */
  AUTOCOMPLETE_KEY_CCL_USER_TO: 'CCL_USER_TO',
  /** 监管证件 */
  AUTOCOMPLETE_KEY_CCL_LICENSE_DOCU: 'AUTOCOMPLETE_KEY_CCL_LICENSE_DOCU',
  /** 企业资质 */
  AUTOCOMPLETE_KEY_CCL_COP_LIMIT: 'AUTOCOMPLETE_KEY_CCL_COP_LIMIT',

  /** 海关编码 */
  AUTOCOMPLETE_KEY_CUSTOMS_CODE: 'CUSTOMS_CODE',
  /** 进口订单 */
  AUTOCOMPLETE_KEY_IMPORT_ORDER: 'IMPORT_ORDER',
  /** 出口订单 */
  AUTOCOMPLETE_KEY_EXPORT_ORDER: 'EXPORT_ORDER',
  /** 代采订单 */
  AUTOCOMPLETE_KEY_AGENT_PURCHASE_ORDER: 'AGENT_PURCHASE_ORDER',
  /** 代销订单 */
  AUTOCOMPLETE_KEY_AGENT_SALE_ORDER: 'AGENT_SALE_ORDER',
  /** 销售订单 */
  AUTOCOMPLETE_KEY_SALE_ORDER: 'SALE_ORDER',
  /** 采购订单 */
  AUTOCOMPLETE_KEY_PURCHASE_ORDER: 'PURCHASE_ORDER',
  /** 货代订单 */
  AUTOCOMPLETE_KEY_AGENT_FREIGHT_ORDER: 'AGENT_FREIGHT_ORDER',
  /** 仓储订单 */
  AUTOCOMPLETE_KEY_STORAGE_ORDER: 'STORAGE_ORDER',
  /** 报关名称 */
  AUTOCOMPLETE_KEY_CUSTOMS_NAME_DECLAR: 'CUSTOMS_NAME_DECLAR',
  /** 付款单 */
  AUTOCOMPLETE_KEY_ACCT_PAYMENT: 'ACCT_PAYMENT',
  /** 收款单 */
  AUTOCOMPLETE_KEY_ACCT_RECEIPT: 'ACCT_RECEIPT',
  /** 报关单 */
  AUTOCOMPLETE_KEY_CUSTOMS_ORDER_DECLAR: 'CUSTOMS_ORDER_DECLAR',
  /** 报关运输单 */
  AUTOCOMPLETE_KEY_CUSTOMS_ORDER_TRANSPORT_DECLAR: 'CUSTOMS_ORDER_TRANSPORT_DECLAR'
}
