/** 参数管理 */
export default {
  /** 压缩图片配置 */
  PARAMS_COMPRESS: 'COMPRESS',
  /** 在线系统配置 */
  PARAMS_ONLINE_SYSTEM_CONFIG: 'ONLINE_SYSTEM_CONFIG',
  /** （进口）报关单配置 */
  PARAMS_IMPORT_CUSTOMS_MASTER: 'IMPORT_CUSTOMS_MASTER',
  /** （出口）报关单配置 */
  PARAMS_EXPORT_CUSTOMS_MASTER: 'EXPORT_CUSTOMS_MASTER',
  /** 出库默认配置 */
  PARAMS_SHIPPING_DEFAULT: 'SHIPPING_DEFAULT',
  /** 仓库默认配置 */
  PARAMS_DEFAULT_WAREHOUSE: 'DEFAULT_WAREHOUSE',
  /** 默认税点配置 */
  PARAMS_TAX_POINT: 'TAX_POINT',
  /** 报关审价配置 */
  PARAMS_ABNORMAL_PRICE_SCOPE: 'ABNORMAL_PRICE_SCOPE',
  /** 代采差价配置 */
  PARAMS_SPREAD_AGENT_PURCHASE: 'SPREAD_AGENT_PURCHASE',
  /** 短信消息配置 */
  PARAMS_SMS_CONFIG: 'SMS_CONFIG',
  /** 邮件消息配置 */
  PARAMS_EMAIL_CONFIG: 'EMAIL_CONFIG',
  /** 报关单企业资质承诺 */
  PARAMS_CUSTOMS_QUALIF_PROMISE: 'CUSTOMS_QUALIF_PROMISE',
  /** 进/出口归类默认配置 */
  PARAMS_ORDER_CLASSIFIED: 'ORDER_CLASSIFIED',
  /** 结/付汇参数配置 */
  PARAMS_FINANCE_SETTLEMENT_CONFIG: 'FINANCE_SETTLEMENT_CONFIG'
}
