export default {
  /** base-autocomplete-basic 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_BASIC: 'BASE_AUTOCOMPLETE_BASIC',
  /** base-autocomplete-ccl 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_CCL: 'BASE_AUTOCOMPLETE_CCL',
  /** base-autocomplete-formula 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_FORMULA: 'BASE_AUTOCOMPLETE_FORMULA',
  /** base-autocomplete-bank 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_BANK: 'BASE_AUTOCOMPLETE_BANK',
  /** base-autocomplete-product 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_PRODUCT: 'BASE_AUTOCOMPLETE_PRODUCT',
  /** base-autocomplete-warehouse 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_WAREHOUSE: 'BASE_AUTOCOMPLETE_WAREHOUSE',
  /** base-autocomplete-vehicle 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_VEHICLE: 'BASE_AUTOCOMPLETE_VEHICLE',
  /** base-autocomplete-driver 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_DRIVER: 'BASE_AUTOCOMPLETE_DRIVER',
  /** base-autocomplete-cus-customer 定义的表格 name */
  TABLE_NAME_BASE_AUTOCOMPLETE_CUS_CUSTOMER: 'BASE_AUTOCOMPLETE_CUS_CUSTOMER',

  /** 业务导出组件 */
  TABLE_NAME_BUSINESS_EXPORT: 'BUSINESS_EXORT',

  /** 系统操作 */
  /** 用户管理 */
  TABLE_NAME_SYS_USER: 'SYS_USER',
  /** 日志 */
  TABLE_NAME_SYS_LOG: 'SYS_LOG',
  /** 令牌 */
  TABLE_NAME_SYS_TOKEN: 'SYS_TOKEN',
  /** 密钥 */
  TABLE_NAME_SYS_SOCIAL: 'SYS_SOCIAL',
  /** 系统编码 */
  TABLE_NAME_SYS_NO: 'SYS_NO',
  /** 字典管理 */
  TABLE_NAME_SYS_DICT: 'SYS_DICT',
  /** 字典项管理 */
  TABLE_NAME_SYS_DICT_ITEM: 'SYS_DICT_ITEM',
  /** 参数管理 */
  TABLE_NAME_SYS_PUBLIC_PARAM: 'SYS_PUBLIC_PARAM',
  /** 终端管理 */
  TABLE_NAME_SYS_CLIENT: 'SYS_CLIENT',
  /** 报表配置 */
  TABLE_NAME_SYS_REPORT_CONFIG: 'SYS_REPORT_CONFIG',
  /** 在线公告 */
  TABLE_NAME_SYS_CUS_NOTICE: 'SYS_CUS_NOTICE',
  /** 系统公告   */
  TABLE_NAME_SYS_NOTICE: 'SYS_NOTICE',
  /** 主体公司 */
  TABLE_NAME_SUB_COMPANY: 'SUB_COMPANY',
  /** 角色管理 */
  TABLE_NAME_SYS_ROLE: 'SYS_ROLE',

  /** 基础数据 */
  /** 仓库 */
  TABLE_NAME_WAREHOUSE: 'WAREHOUSE',
  /** 币别 */
  TABLE_NAME_CURRENCY: 'CURRENCY',
  /** 海关汇率 */
  TABLE_NAME_CUSTOMS_RATE: 'CUSTOMS_RATE',
  /** 菜单管理-数据权限表格 */
  TABLE_NAME_MENU_VIEW_RULE: 'MENU_VIEW_RULE',
  /** 外汇汇率 */
  TABLE_NAME_BASE_FOREIGN_RATE: 'BASE_FOREIGN_RATE',
  /** 记账汇率 */
  TABLE_NAME_ACCOUNT_RATE: 'ACCOUNT_RATE',
  /** 税收分类 */
  TABLE_NAME_BASE_TAX_CATE: 'BASE_TAX_CATE',
  /** 费用类目 */
  TABLE_NAME_BASE_COST_ITEM: 'BASE_COST_ITEM',
  /** 结算公式配置 */
  TABLE_NAME_BASE_SET_FORMULA: 'SET_FORMULA',
  /** 加征关税 */
  TABLE_NAME_BASE_ADD_TARIFF: 'BASE_ADD_TARIFF',
  /** 申报单位转换 */
  TABLE_NAME_UNIT_CONVER: 'UNIT_CONVER',
  /** 协定关税 */
  TABLE_NAME_BASE_AGREED_TARIFF: 'BASE_AGREED_TARIFF',
  /** 凭证模板 */
  TABLE_NAME_VOUCHER_TEMP: 'VOUCHER_TEMP',
  /** 凭证模板录入表格 */
  TABLE_NAME_VOUCHER_TEMP_ENTER: 'VOUCHER_TEMP_ENTER',
  /** 流程管理 */
  TABLE_NAME_PROCESS: 'PROCESS',
  /** 定时任务 */
  TABLE_NAME_JOB_MANAGE: 'JOB_MANAGE',
  /** 海关编码 */
  TABLE_NAME_BASE_HS_CODE: 'BASE_HS_CODE',
  /** 海关编码-商品申报要素信息录入 */
  TABLE_NAME_BASE_HS_CODE_CLASSIFY_ELEMENTS_ENTER: 'BASE_HS_CODE_CLASSIFY_ELEMENTS_ENTER',
  /** 海关编码-CIQ编码录入 */
  TABLE_NAME_BASE_HS_CODE_CIQ_ENTER: 'BASE_HS_CODE_CIQ_ENTER',
  /** 海关编码-商品申报要素信息详情 */
  TABLE_NAME_BASE_HS_CODE_CLASSIFY_ELEMENTS_DETAILS: 'BASE_HS_CODE_CLASSIFY_ELEMENTS_DETAILS',
  /** 海关编码-CIQ编码详情 */
  TABLE_NAME_BASE_HS_CODE_CIQ_DETAILS: 'BASE_HS_CODE_CIQ_DETAILS',
  /** 报关单ciq */
  TABLE_NAME_CUS_CIQ: 'CUS_CIQ',

  /** 商品单位 */
  TABLE_NAME_PRODUCT_UNIT: 'PRODUCT_UNIT',
  /** 商品信息 */
  TABLE_NAME_PRODUCT_INFO: 'PRODUCT_INFO',
  /** 品牌库 */
  TABLE_NAME_PRODUCT_BRAND: 'PRODUCT_BRAND',
  /** 申报单位转换 */
  TABLE_NAME_PRODUCT_CONTROL: 'PRODUCT_CONTROL',

  /** 进口预归类 */
  TABLE_NAME_CLASSIFY_BILL_IMPORT: 'CLASSIFY_BILL_IMPORT',
  /** 进口预归类-批量归类表格 */
  TABLE_NAME_CLASSIFY_BILL_IMPORT_CLASSIFY_BATCH: 'CLASSIFY_BILL_IMPORT_CLASSIFY_BATCH',
  /** 出口预归类 */
  TABLE_NAME_CLASSIFY_BILL_EXPORT: 'CLASSIFY_BILL_EXPORT',
  /** 出口预归类-批量归类表格 */
  TABLE_NAME_CLASSIFY_BILL_EXPORT_CLASSIFY_BATCH: 'CLASSIFY_BILL_EXPORT_CLASSIFY_BATCH',
  /** 商品归类库 */
  TABLE_NAME_CLASSIFY: 'CLASSIFY',
  /** 商品归类库-批量归类表格 */
  TABLE_NAME_CLASSIF_BATCH: 'CLASSIFY_BATCH',
  /** 报关名称归类库 */
  TABLE_NAME_CLEAR_CLASSIFY: 'CLEAR_CLASSIFY',
  /** 进口审价 */
  TABLE_NAME_PRICE_REVIEW_IMPORT: 'PRICE_REVIEW_IMPORT',
  /** 进口审价明细信息 */
  TABLE_NAME_PRICE_REVIEW_IMPORT_DETAILS: 'PRICE_REVIEW_IMPORT_DETAILS',
  /** 进口审价-查看历史价格-报关明细 */
  TABLE_NAME_PRICE_REVIEW_IMPORT_CUSTOMS_DETAILS: 'PRICE_REVIEW_IMPORT_CUSTOMS_DETAILS',
  /** 出口审价 */
  TABLE_NAME_PRICE_REVIEW_EXPORT: 'PRICE_REVIEW_EXPORT',
  /** 出口审价明细信息 */
  TABLE_NAME_PRICE_REVIEW_EXPOR_DETAILST: 'PRICE_REVIEW_EXPORT_DETAILS',
  /**  出口审价-查看历史价格-报关明细 */
  TABLE_NAME_PRICE_REVIEW_EXPOR_CUSTOMS_DETAILS: 'PRICE_REVIEW_EXPOR_CUSTOMS_DETAILS',
  /** 历史价格库 */
  TABLE_NAME_CUS_HI_PRICE: 'CUS_HI_PRICE',
  /** 历史价格库-报关单明细 */
  TABLE_NAME_CUS_HI_PRICE_CUSTOMS_DETAILS: 'CUS_HI_PRICE_CUSTOMS_DETAILS',
  /** 绑定报关单待选区表格 */
  TABLE_NAME_CUSTOMS_BIDN_WAIT: 'CUSTOMS_BIDN_BIDN',
  /** 绑定报关单已选区表格 */
  TABLE_NAME_CUSTOMS_BIDN_SELECT: 'CUSTOMS_BIDN_SELECT',

  /** 通关参数 */
  /** 监管方式代码 */
  TABLE_NAME_CUS_TRADE: 'CUS_TRADE',
  /** 征免性质代码 */
  TABLE_NAME_CUS_LEVY_TYPE: 'CUS_LEVY_TYPE',
  /** 国别(地区) */
  TABLE_NAME_CUS_COUNTRY: 'CUS_COUNTRY',
  /** 国内(地区) */
  TABLE_NAME_CUS_DISTRICT: 'CUS_DISTRICT',
  /** 关区代码 */
  TABLE_NAME_CUS_CUSTOMS: 'CUS_CUSTOMS',
  /** 币制代码 */
  TABLE_NAME_CUS_CURRENCY: 'CUS_CURRENCY',
  /** 计量单位 */
  TABLE_NAME_CUS_UNIT: 'CUS_UNIT',
  /** 监管证件 */
  TABLE_NAME_CUS_LICENSE_DOC: 'CUS_LICENSE_DOC',
  /** 地区性质代码 */
  TABLE_NAME_CUS_REGION: 'CUS_REGION',
  /** 成交方式代码 */
  TABLE_NAME_CUS_TRANSACT: 'CUS_TRANSACT',
  /** 用途代码 */
  TABLE_NAME_CUS_USED_TO: 'CUS_USED_TO',
  /** 结汇方式代码 */
  TABLE_NAME_CUS_SETTLEMENT: 'CUS_SETTLEMENT',
  /** 运输方式代码 */
  TABLE_NAME_CUS_TRANSF: 'CUS_TRANSF',
  /** 征减免税代码 */
  TABLE_NAME_CUS_LEVYMODE: 'CUS_LEVYMODE',
  /** 企业性质代码 */
  TABLE_NAME_CUS_PERSON: 'CUS_PERSON',
  /** 包装种类代码 */
  TABLE_NAME_CUS_PACKING_TYPE: 'cus_packing_type',
  /** 港口代码 */
  TABLE_NAME_CUS_PORT: 'CUS_PORT',
  /** 口岸代码 */
  TABLE_NAME_CUS_ENTRY_PORT: 'CUS_ENTRY_PORT',
  /** 检验检疫机关代码 */
  TABLE_NAME_CUS_ORG_CODE: 'CUS_ORG_CODE',
  /** 原产地区代码 */
  TABLE_NAME_CUS_ORIG_PLACE: 'CUS_ORIG_PLACE',
  /** 国内行政区划代码 */
  TABLE_NAME_CUS_DEST: 'CUS_DEST',
  /** 货物属性代码 */
  TABLE_NAME_CUS_GOODS_ATTR: 'CUS_GOODS_ATTR',
  /** 集装箱规格代码 */
  TABLE_NAME_CUS_CONTAINER_FORMAT: 'CUS_CONTAINER_FORMAT',
  /** 企业资质代码 */
  TABLE_NAME_CUS_COP_LIMIT: 'CUS_COP_LIMIT',

  /** 业务中心 */
  /** B2B认证 */
  TABLE_NAME_CUS_AUTH: 'CUS_AUTH',

  /** 委托客户 */
  TABLE_NAME_CUSTOMER: 'CUSTOMER',
  /** 委托客户 --》 收货信息 */
  TABLE_NAME_CUSTOMER_DELIVERYINFO: 'CUSTOMER_DELIVERYINFO',
  /** 委托客户 --》开票资料 */
  TABLE_NAME_CUSTOMER_INVOICE: 'CUSTOMER_INVOICE',
  /** 委托客户 --》银行资料 */
  TABLE_NAME_CUSTOMER_BANK: 'CUSTOMER_BANK',
  /** 委托客户 --》联系人资料 */
  TABLE_NAME_CUSTOMER_PERSON: 'CUSTOMER_PERSON',
  /** 委托客户 --》客户维护人 */
  TABLE_NAME_CUSTOMER_ADVOCATE: 'CUSTOMER_ADVOCATE',
  /** 委托客户 --》服务协议 */
  TABLE_NAME_CUSTOMER_AGREE: 'CUSTOMER_AGREE',
  /** 委托客户 --》销售客户 */
  TABLE_NAME_CUSTOMER_CUS_CUSTOMER: 'CUSTOMER_CUS_CUSTOMER',
  /** 委托客户 --》B2B用户 */
  TABLE_NAME_CUSTOMER_ONLINE: 'CUSTOMER_ONLINE',

  /** 服务协议 */
  TABLE_NAME_SERVICE_AGREE: 'SERVICE_AGREE',
  /** 服务协议模板 */
  TABLE_NAME_SERVICE_AGREE_TEMPLATE: 'SERVICE_AGREE_TEMPLATE',
  /** 供应商 */
  TABLE_NAME_SUPPLIER: 'SUPPLIER',
  /** 供应商 - 交货信息 */
  TABLE_NAME_SUPPLIER_DELIVERY: 'SUPPLIER_DELIVERY',
  /** 报关行 */
  TABLE_NAME_CUSTOMS: 'CUSTOMS',
  /** 承运商 */
  TABLE_NAME_TRANSPORT: 'TRANSPORT',
  /** 承运商-司机 */
  TABLE_NAME_TRANSPORT_DRIVER: 'TRANSPORT_DRIVER',
  /** 承运商-车辆 */
  TABLE_NAME_TRANSPORT_VEHICLE: 'TRANSPORT_VEHICLE',
  /** 进口订单 */
  TABLE_NAME_IMPORT_ORDER: 'IMPORT_ORDER',
  /** 进口订单录入表格 */
  TABLE_NAME_IMPORT_ORDER_ENTER: 'IMPORT_ORDER_ENTER',
  /** 进口订单详情表格 */
  TABLE_NAME_IMPORT_ORDER_DETAILS: 'IMPORT_ORDER_DETAILS',
  /** 进口订单详情配件列表 */
  TABLE_NAME_IMPORT_ORDER_PARTS: 'IMPORT_ORDER_PARTS',

  /** 出口订单 */
  TABLE_NAME_EXPORT_ORDER: 'EXPORT_ORDER',
  /** 出口订单录入表格 */
  TABLE_NAME_EXPORT_ORDER_ENTER: 'EXPORT_ORDER_ENTER',
  /** 出口订单详情表格 */
  TABLE_NAME_EXPORT_ORDER_DETAILS: 'EXPORT_ORDER_DETAILS',
  /** 出口订单详情配件列表 */
  TABLE_NAME_EXPORT_ORDER_PARTS: 'EXPORT_ORDER_PARTS',

  /** 代采订单 */
  TABLE_NAME_DOMESTIC_ORDER: 'DOMESTIC_ORDER',
  /** 代采订单录入表格 */
  TABLE_NAME_DOMESTIC_ORDER_ENTER: 'DOMESTIC_ORDER_ENTER',
  /** 代采订单详情表格 */
  TABLE_NAME_DOMESTIC_ORDER_DETAILS: 'DOMESTIC_ORDER_DETAILS',
  /** 采购订单 */
  TABLE_NAME_PURCHASE_ORDER: 'PURCHASE_ORDER',
  /** 采购订单录入表格 */
  TABLE_NAME_PURCHASE_ORDER_ENTER: 'PURCHASE_ORDER_ENTER',
  /** 采购订单详情表格 */
  TABLE_NAME_PURCHASE_ORDER_DETAILS: 'PURCHASE_ORDER_DETAILS',
  /** 销售订单 */
  TABLE_NAME_SALE_ORDER: 'SALE_ORDER',
  /** 销售订单录入表格 */
  TABLE_NAME_SALE_ORDER_ENTER: 'SALE_ORDER_ENTER',
  /** 销售订单详情表格 */
  TABLE_NAME_SALE_ORDER_DETAILS: 'SALE_ORDER_DETAILS',
  /** 代销订单 */
  TABLE_NAME_BUS_CONSIGN: 'BUS_CONSIGN',
  /** 代销订单录入表格 */
  TABLE_NAME_BUS_CONSIGN_ENTER: 'BUS_CONSIGN_ENTER',
  /** 代销订单详情表格 */
  TABLE_NAME_BUS_CONSIGN_DETAILS: 'BUS_CONSIGN_DETAILS',
  /** 基差合同 */
  TABLE_NAME_BASIS_ORDER: 'BASIS',
  /** 基差合同录入表格 */
  TABLE_NAME_BASIS_ORDER_ENTER: 'BASIS_ORDER_ENTER',
  /** 基差合同详情表格 */
  TABLE_NAME_BASIS_ORDER_DETAILS: 'BASIS_ORDER_DETAILS',
  /** 货代订单 */
  TABLE_NAME_BUS_FREIGHT: 'BUS_FREIGHT',
  /** 货代订单录入表格 */
  TABLE_NAME_PURCHASE_BUS_FREIGHT_ORDER: 'BUS_FREIGHT_ORDER_ENTER',
  /** 货代订单详情表格 */
  TABLE_NAME_PURCHASE_BUS_FREIGHT_ORDER_DETAILS: 'BUS_FREIGHT_ORDER_DETAILS',
  /** 仓储订单 */
  TABLE_NAME_BUS_STORAGE_ORDER: 'BUS_STORAGE',
  /** 仓储订单录入表格 */
  TABLE_NAME_PURCHASE_BUS_STORAGE_ORDER: 'BUS_STORAGE_ORDER_ENTER',
  /** 仓储订单详情表格 */
  TABLE_NAME_BUS_STORAGE_ORDER_DETAILS: 'BUS_STORAGE_ORDER_DETAILS',

  /** 仓储物流 */
  /** 收货记录 */
  TABLE_NAME_RECEIVING_RECORD: 'RECEIVING_RECORD',
  /** 入库单 */
  TABLE_NAME_WARE_RECEIVING: 'WARE_RECEIVING',
  /** 入库单录入表格  */
  TABLE_NAME_WARE_RECEIVING_ENTER: 'WARE_RECEIVING_ENTER',
  /** 入库单详情表格 */
  TABLE_NAME_WARE_RECEIVING_DETAILS: 'WARE_SHIPPING_DETAILS',
  /** 入库单生成商品订单查询表格 */
  TABLE_NAME_WARE_RECEIVING_ORDER_SELECT_DETAILS: 'WARE_RECEIVING_ORDER_SELECT_DETAILS',

  /** 出库单 */
  TABLE_NAME_WARE_SHIPPING: 'WARE_SHIPPING',
  /** 出库单录入表格 */
  TABLE_NAME_WARE_SHIPPING_ENTER: 'WARE_SHIPPING_ENTER',
  /** 出库单详情表格 */
  TABLE_NAME_WARE_SHIPPING_DETAILS: 'WARE_SHIPPING_DETAILS',
  /** 出库费用表格 */
  TABLE_NAME_WARE_SHIPPING_COST: 'WARE_SHIPPING_COST',
  /** 出库费用录入表格 */
  TABLE_NAME_WARE_SHIPPING_COST_ENTER: 'WARE_SHIPPING_COST_ENTER',

  /** 出库单生成商品订单查询表格 */
  TABLE_NAME_WARE_SHIPPING_ORDER_SELECT_DETAILS: 'WARE_SHIPPING_ORDER_SELECT_DETAILS',
  /** 出库单验货明细表格 */
  TABLE_NAME_WARE_SHIPPING_CHECK: 'WARE_SHIPPING_CHECK',
  /** 出库单验货明细拆分功能a表格 */
  TABLE_NAME_WARE_SHIPPING_CHECK_SPLIT_A: 'WARE_SHIPPING_CHECK_SPLIT_A',
  /** 出库单验货明细拆分功能b表格 */
  TABLE_NAME_WARE_SHIPPING_CHECK_SPLIT_B: 'WARE_SHIPPING_CHECK_SPLIT_B',
  /** 出库单验货明细批量修改表格 */
  TABLE_NAME_WARE_SHIPPING_CHECK_BATCH_EDIT: 'WARE_SHIPPING_CHECK_BATCH_EDIT',
  /** 出库单备货明细表格 */
  TABLE_NAME_WARE_SHIPPING_STOCK: 'WARE_SHIPPING_STOCK',

  /** 库存记录 */
  TABLE_NAME_STOCK: 'STOCK',
  /** 库存记录 */
  TABLE_NAME_STOCK_MATCH: 'STOCK_MATCH',
  /** 收货记录 */
  TABLE_NAME_BUS_IMPORT_RECEIVING: 'BUS_IMPORT_RECEIVING',
  /** 库存记录 */
  TABLE_NAME_COMMON_STOCK: 'COMMON_STOCK',
  /** 出库记录 */
  TABLE_NAME_COMMON_SHIPPING: 'COMMON_SHIPPING',
  /** 入库记录 */
  TABLE_NAME_COMMON_RECEIVE: 'COMMON_RECEIVE',
  /** 入库异常记录 */
  TABLE_NAME_COMMON_EXCEPTION: 'COMMON_EXCEPTION',
  /** 报关单(tabs) */
  TABLE_NAME_COMMOM_CUSTOMS: 'COMMOM_CUSTOMS',
  /** 操作日志 */
  TABLE_NAME_COMMOM_OPR_RECORDS: 'COMMOM_OPR_RECORDS',
  /** 应收类目(tabs) */
  TABLE_NAME_COMMON_ACCT_COST_INVO: 'COMMON_ACCT_COST_INVO',
  /** 应付类目(tabs) */
  TABLE_NAME_COMMOM_ACCT_COST_PAY: 'COMMOM_ACCT_COST_PAY',

  /** 物流管理 */
  /** 报关运输单 */
  TABLE_NAME_HG_TRUCK: 'HG_TRUCK',
  /** 报关运输单录入表格 */
  TABLE_NAME_HG_TRUCK_ENTER: 'HG_TRUCK_ENTER',
  /** 报关运输单详情表格 */
  TABLE_NAME_HG_TRUCK_DETAILS: 'HG_TRUCK_DETAILS',
  /** 报关运输单-报关单 */
  TABLE_NAME_HG_TRUCK_CUSTOMS_MASTER: 'HG_TRUCK_CUSTOMS_MASTER',
  /** 快递发货单 */
  TABLE_NAME_EXPRESS_NO: 'EXPRESS_NO',
  /** 快递发货单录入表格 */
  TABLE_NAME_EXPRESS_NO_ENTER: 'EXPRESS_NO_ENTER',
  /** 快递发货单详情表格 */
  TABLE_NAME_EXPRESS_NO_DETAILS: 'EXPRESS_NO_DETAILS',
  /** 快递发货单生成表格 */
  TABLE_NAME_EXPRESS_NO_CREATE: 'EXPRESS_NO_CREATE',
  /** 客户自提单  */
  TABLE_NAME_TAKE_NO: 'TAKE_NO',
  /** 客户自提单录入表格 */
  TABLE_NAME_TAKE_NO_ENTER: 'TAKE_NO_ENTER',
  /** 客户自提单详情表格 */
  TABLE_NAME_TAKE_NO_DETAILS: 'TAKE_NO_DETAILS',
  /** 客户自提单生成表格 */
  TABLE_NAME_TAKE_NO_CREATE: 'TAKE_NOO_CREATE',
  /** 调度送货单 */
  TABLE_NAME_DISPATCH_NO: 'DISPATCH_NO',
  /** 调度送货单录入表格 */
  TABLE_NAME_DISPATCH_NO_ENTER: 'DISPATCH_NO_ENTER',
  /** 调度送货单详情表格 */
  TABLE_NAME_DISPATCH_NO_DETAILS: 'DISPATCH_NO_DETAILS',
  /** 调度送货单生成表格 */
  TABLE_NAME_DISPATCH_NO_CREATE: 'DISPATCH_NO_CREATE',

  /** 进口跨境订车计划 */
  TABLE_NAME_TRANSPORT_PLAN_IMPORT: 'TRANSPORT_PLAN_IMPORT',
  /** 出口跨境订车计划 */
  TABLE_NAME_TRANSPORT_PLAN_EXPORT: 'TRANSPORT_PLAN_EXPORT',

  /** 财务管理 */
  /** 应收类目 */
  TABLE_NAME_ACCT_COST_INVOICE: 'ACCT_COST_INVOICE',
  /** 应收类目录入表格 */
  TABLE_NAME_ACCT_COST_INVO_ENTER: 'ACCT_COST_INVO_ENTER',
  /** 应收类目详情表格 */
  TABLE_NAME_BUS_IMPORT_ACCT_COST_INVO_DETAILS: 'ACCT_COST_INVO_DETAILS',
  /** 收款单 */
  TABLE_NAME_ACCT_RECEIPT: 'ACCT_RECEIPT',
  /** 收款单付汇记录  */
  TABLE_NAME_ACCT_RECEIPT_PAYMENT: 'ACCT_RECEIPT_PAYMENT',
  /** 收款单付汇记录-查询未付汇的订单  */
  TABLE_NAME_ACCT_RECEIPT_PAYMENT_FOR_NO_PAY: 'ACCT_RECEIPT_PAYMENT_FOR_NO_PAY',
  /** 收款单结汇信息  */
  TABLE_NAME_ACCT_RECEIPT_SETTLE_A: 'ACCT_RECEIPT_SETTLE_A',
  /** 收款单结汇记录  */
  TABLE_NAME_ACCT_RECEIPT_SETTLE_B: 'ACCT_RECEIPT_SETTLE_B',
  /** 收款单结汇记录-查询未付汇的订单  */
  TABLE_NAME_ACCT_RECEIPT_SETTLE_FOR_NO_SETTLE: 'ACCT_RECEIPT_SETTLE_FOR_NO_SETTLE',
  /** 收款单已核销列表 */
  TABLE_NAME_ACCT_RECEIPT_CONSUMED: 'ACCT_RECEIPT_CONSUMED',
  /** 收款单待核销列表 */
  TABLE_NAME_ACCT_RECEIPT_WAIT: 'ACCT_RECEIPT_WAIT',
  /** 收款单待核销生成功能核销列表 */
  TABLE_NAME_ACCT_RECEIPT_VERIFICATION: 'ACCT_RECEIPT_VERIFICATION',
  /** 收款核销记录  */
  TABLE_NAME_ACCT_RECEIPT_VERIFY: 'ACCT_RECEIPT_VERIFY',

  /** 应付类目 */
  TABLE_NAME_PAY_ORDER_ACC_COST: 'PAY_ORDER_ACC_COST',
  /** 付款单 */
  TABLE_NAME_PAY_ORDER: 'PAY_ORDER',
  /** 付款单录入表格 */
  TABLE_NAME_PAY_ORDER_ENTER: 'PAY_ORDER_ENTER',
  /** 付款单详情表格 */
  TABLE_NAME_PAY_ORDER_DETAILS: 'PAY_ORDER_DETAILS',
  /** 付款单已核销列表 */
  TABLE_NAME_PAY_ORDER_CONSUMED: 'PAY_ORDER_CONSUMED',
  /** 付款单待核销列表 */
  TABLE_NAME_PAY_ORDER_WAIT: 'PAY_ORDER_WAIT',
  /** 付款单付款单明细生成表格 */
  TABLE_NAME_PAY_ORDER_DETAILS_CREATE: 'PAY_ORDER_DETAILS_CREATE',
  /** 付款单核销记录  */
  TABLE_NAME_ACCT_PAYMENT_VERIFY: 'ACCT_PAYMENT_VERIFY',
  /** 付款单待核销生成功能核销列表 */
  TABLE_NAME_ACCT_PAYMENT_VERIFICATION: 'ACCT_PAYMENT_VERIFICATION',

  /** 销项票 */
  TABLE_NAME_SALES_TICKET: 'SALES_TICKET',
  /** 销项票开票订单 */
  TABLE_NAME_SALES_TICKET_INVOICE_ENTER: 'SALES_TICKET_INVOICE_ENTER',
  /** 销项票服务费项目 */
  TABLE_NAME_SALES_TICKET_SERVICE_ENTER: 'SALES_TICKET_SERVICE_ENTER',
  /** 销项票开票关联票差 */
  TABLE_NAME_SALES_TICKET_DIFF_VOT_ENTER: 'SALES_TICKET_DIFF_VOT_ENTER',
  /** 销项票开票商品明细 */
  TABLE_NAME_SALES_TICKET_GOODS_ENTER: 'SALES_TICKET_GOODS_ENTER',
  /** 销项票开票订单生成 */
  TABLE_NAME_SALES_TICKET_INVOICE_CREATE: 'SALES_TICKET_INVOICE_CREATE',
  /** 销项票服务费项目生成 */
  TABLE_NAME_SALES_TICKET_SERVICE_CREATE: 'SALES_TICKET_SERVICE_CREATE',
  /** 销项票开票关联票差生成 */
  TABLE_NAME_SALES_TICKET_DIFF_VOT_CREATE: 'SALES_TICKET_DIFF_VOT_CREATE',
  /** 销项票开票商品明细生成 */
  TABLE_NAME_SALES_TICKET_GOODS_CREATE: 'SALES_TICKET_GOODS_CREATE',
  /** 销项票发票明细详情 */
  TABLE_NAME_SALES_TICKET_INVOICE_DETAILS: 'SALES_TICKET_INVOICE_DETAILS',
  /** 销项票服务费项目详情 */
  TABLE_NAME_SALES_TICKET_SERVICE_DETAILS: 'SALES_TICKET_SERVICE_DETAILS',
  /** 销项票开票关联票差详情 */
  TABLE_NAME_SALES_TICKET_DIFF_VOT_DETAILS: 'SALES_TICKET_DIFF_VOT_DETAILS',
  /** 销项票开票商品明细详情 */
  TABLE_NAME_SALES_TICKET_GOODS_DETAILS: 'SALES_TICKET_GOODS_DETAILS',

  /** 进项票 */
  TABLE_NAME_INPUT_TICKET: 'INPUT_TICKET',
  /** 进项票录入表格 */
  TABLE_NAME_INPUT_TICKET_ENTER: 'INPUT_TICKET_ENTER',
  /** 进项票详情表格 */
  TABLE_NAME_INPUT_TICKET_DETAILS: 'INPUT_TICKET_DETAILS',
  /** 进项票生成表格 */
  TABLE_NAME_INPUT_TICKET_CREATE: 'INPUT_TICKET_CREATE',
  /** 退税申报 */
  TABLE_NAME_TAX_DECLARE: 'TAX_DECLARE',
  /** 进口票差  */
  TABLE_NAME_IMPORT_TICKET_DIFF: 'IMPORT_TICKET_DIFF',
  /** 进口票差详情表格  */
  TABLE_NAME_IMPORT_TICKET_DIFF_DETAILS: 'IMPORT_TICKET_DIFF_DETAILS',
  /** 退税申报-订单票差 */
  TABLE_NAME_TAX_DECLARE_ORDER_INVOICE: 'tax_declare_order_invoice',

  /** 银承汇票 */
  TABLE_NAME_ACCT_BANK_ACCEPTANCE: 'ACCT_BANK_ACCEPTANCE',
  /** 银承汇票录入表格 */
  TABLE_NAME_ACCT_BANK_ACCEPTANCE_ENTER: 'ACCT_BANK_ACCEPTANCE_ENTER',
  /** 银承汇票详情表格 */
  TABLE_NAME_ACCT_BANK_ACCEPTANCE_DETAILS: 'ACCT_BANK_ACCEPTANCE_DETAILS',

  /** 开证 */
  TABLE_NAME_ACCT_CREDIT_ISSUING: 'ACCT_CREDIT_ISSUING',
  /** 开证到单 */
  TABLE_NAME_ACCT_CREDIT_ISSUING_ARRIVAL: 'ACCT_CREDIT_ISSUING_ARRIVA',
  /** 收证 */
  TABLE_NAME_ACCT_CREDIT_RECEIPT: 'ACCT_CREDIT_RECEIPT',
  /** 收证交单 */
  TABLE_NAME_ACCT_CREDIT_RECEIPT_PRESENT: 'ACCT_CREDIT_RECEIPT_PRESENT',

  /** 额度授信 */
  TABLE_NAME_QUOTA_RECORD: 'QUOTA_RECORD',
  /** 客户额度池  */
  TABLE_NAME_QUOTA: 'QUOTA',

  /** 报关单 */
  TABLE_NAME_CUSTOMS_DECLARATION: 'TABLE_NAME_CUSTOMS_DECLARATION',
  /** 报关单详情 */
  TABLE_NAME_CUSTOMS_DECLARATION_DETAILS: 'TABLE_NAME_CUSTOMS_DECLARATION_DETAILS',
  /** 报关单项号关系*/
  TABLE_NAME_CUSTOMS_DECLARATION_ITEN_NO: 'TABLE_NAME_CUSTOMS_DECLARATION_ITEN_NO',
  /** 报关单-入库单明细 */
  TABLE_NAME_CUSTOMS_RECEIVING_DETAIL: 'CUSTOMS_RECEIVING_DETAIL',

  /** 服务协议比价配置查看表格 */
  TABLE_NAME_CONTRACT_AGENCY_PRICE: 'CONTRACT_AGENCY_PRICE',
  /** 服务协议比价配置编辑表格 */
  TABLE_NAME_CONTRACT_AGENCY_PRICE_ENTER: 'CONTRACT_AGENCY_PRICE_ENTER',
  /** 附件 */
  TABLE_NAME_ANNEX: 'ANNEX',
  /** 通知模板 */
  TABLE_NAME_NOTICE_TEMPLATE: 'NOTICE_TEMPLATE'
}
